name: CI/CD Pipeline for psychotherapist-office-REST

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Pobierz kod z repozytorium
      - name: Checkout code
        uses: actions/checkout@v4

      # Krok 2: Ustaw środowisko Java (dostosuj wersję do potrzeb projektu)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Krok 3: Zainstaluj zależności i zbuduj projekt z Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Krok 4: Uruchom testy jednostkowe
      - name: Run tests
        run: mvn test

      # Krok 5: (Opcjonalne) Prześlij artefakty (np. plik .jar)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: psychotherapist-office-REST
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' # Wdrażaj tylko na branchu main

    steps:
      # Krok 1: Pobierz kod
      - name: Checkout code
        uses: actions/checkout@v4

      # Krok 2: Ustaw środowisko Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Krok 3: (Przykładowe) Wdrożenie na serwer (np. Heroku, AWS, itp.)
      # Zastąp ten krok odpowiednią konfiguracją dla Twojego serwera
      - name: Deploy to production
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          echo "Deploying to production server..."
          # Przykład: skopiuj artefakt na serwer lub użyj API platformy
          # curl -X POST -H "Authorization: Bearer $DEPLOY_TOKEN" -F "file=@target/*.jar" https://your-deployment-api
