name: Java CI with Gradle

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build and test with Gradle
        run: ./gradlew --no-daemon clean test -Dspring.profiles.active=dev

      - name: Generate JaCoCo coverage report
        if: always()
        run: ./gradlew jacocoTestReport --no-daemon

      - name: Upload test results (JUnit XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-xml
          path: build/test-results/test

      - name: Upload test report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report-html
          path: build/reports/tests/test

      - name: Upload JaCoCo report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html
          path: build/reports/jacoco/test